# 回调地狱解决方式

## 概念导读

**回调函数：**当一个函数传入另一个参数中，不会立即执行，只有满足一定条件函数才可以执行，这种函数称之为回调函数。

**同步任务：**同步任务在主线程上排队完成，当前一个任务执行完毕后，才能执行下一个任务。

**异步任务：**不进入主线程，而是进入异步队列，前一个任务是否执行完毕不影响下一个任务的执行。

**回调函数地狱：**在回调中嵌套回调函数，一直嵌套下去就形成了回调函数地狱。

```js
//代码示例
setTimeout(function () {  //第一层
    console.log('第一层');
    setTimeout(function () {  //第二程
        console.log('第二层');
        setTimeout(function () {   //第三层
            console.log('第三层');
        }, 1000)
    }, 2000)
}, 3000)
```

## Promise解决回调地狱

将回调函数嵌套改为链式调用

- Promise对象的then方法用来接收处理成功时响应的数据，catch方法用来接收处理失败时相应的数据。
- Promise的链式编程可以保证代码的执行顺序，前提是每一次在then做完处理后，一定要return一个Promise对象，这样才能在下一次then时接收到数据。

```js
//Promise链式调用解决回调地狱
function fn(str, time) {
    let p = new Promise(function (resolve, reject) {
        setTimeout(() => resolve(str), time);
    })
    return p;
}
fn("promise第一层", 3000).then(res => {
    console.log(res);
    return fn("promise第二层", 2000);
}).then(res => {
    console.log(res);
    return fn("promise第三层", 1000);
}).then(res => {
    console.log(res);
}).catch(res => {
    console.log(res);  //接收失败数据
})
```

## async/await解决回调地狱

`async`和`await`是Promise的语法糖，简化异步代码编写，增加可读性和同步性。

关键字`async`放在声明函数前，表明是一个异步函数，不会阻塞后面函数的执行。

关键字`await`只能在使用`async`定义的函数中使用，可以直接跟一个 Promise实例对象，可以直接拿到Promise中resolve中的数据，不能单独使用。

```js
 async function test() {
    try {
        const res1 = await fn("第一层", 3000);
        const res2 = await fn("第二层", 2000);
        const res3 = await fn("第三层", 1000);
        //等待上述函数都执行完后打印
        console.log(res1, res2, res3);
    } catch (error) {
        console.log(error);
    }
}
test();
```

## 代码示例

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>回调地狱解决方式</title>
</head>

<body>
    <script>
        //回调地狱
        setTimeout(function () {  //第一层
            console.log('第一层');
            setTimeout(function () {  //第二程
                console.log('第二层');
                setTimeout(function () {   //第三层
                    console.log('第三层');
                }, 1000)
            }, 2000)
        }, 3000)
        //Promise链式调用解决回调地狱
        function fn(str, time) {
            let p = new Promise(function (resolve, reject) {
                setTimeout(() => resolve(str), time);
            })
            return p;
        }
        fn("promise第一层", 3000).then(res => {
            console.log(res);
            return fn("promise第二层", 2000);
        }).then(res => {
            console.log(res);
            return fn("promise第三层", 1000);
        }).then(res => {
            console.log(res);
        }).catch(res => {
            console.log(res);  //接收失败数据
        })
        //async/await解决回调地狱
        async function test() {
            try {
                const res1 = await fn("第一层", 3000);
                const res2 = await fn("第二层", 2000);
                const res3 = await fn("第三层", 1000);
                //等待上述函数都执行完后打印
                console.log(res1, res2, res3);
            } catch (error) {
                console.log(error);
            }
        }
        test();
    </script>
</body>

</html>
```

